title: Hamed Adefuwa # your name (or website title) here
logo: "/images/hamed adefuwa cartoon character.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First Year Electrical Engineering Student
  <br><br>
  Bradford, UK 
  <br><br>
  <a href="https://www.linkedin.com/in/hamedadefuwa/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-cayman
google_analytics: UA-160694449-1 # your Google Analytics tracking ID here
